exclude: >
    (?x)^(
        .idea|
        migrations/.*\.py
    )$

default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
    - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    - id: mypy
